name: Deploy Innovatech
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Desplegar en AWS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "innovatech-devops" ]; then
              git clone https://github.com/manque-123/innovatech-devops.git
            fi
            cd innovatech-devops
            git pull origin main
            sudo docker-compose up -d --build